apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  labels:
    app.kubernetes.io/name: guestapp
    app.kubernetes.io/component: app
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: guestapp
      app.kubernetes.io/component: app
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: guestapp
        app.kubernetes.io/component: app
    spec:
      containers:
      - name: guestapp
        image: paulczar/gb-frontend:v5
        
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80